version: "3.7"

services:
  admin-nginx:
    environment:
      VIRTUAL_HOST: admin-nginx
      SYMFONY_ENV: "dev"
      SYMFONY_DEBUG: "1"

  admin-php:
    environment:
      PHP_IDE_CONFIG: "serverName=admin.${DOCKER_BASE_DOMAIN}"
      SYMFONY_ENV: "dev"
      SYMFONY_DEBUG: "1"

  admin-cron:
    environment:
      PHP_IDE_CONFIG: "serverName=cron.${DOCKER_BASE_DOMAIN}"
      SYMFONY_ENV: "dev"
      SYMFONY_DEBUG: "1"

volumes:
  admin-release:
    driver_opts:
      type: none
      device: $PWD/development
      o: bind
